#!/bin/bash
set -e
if [ ! -z "$DEBUG" ]; then
	set -x
fi

if [ -z "$ZOOKEEPER_QUORUM" ]; then
	echo "ZOOKEEPER_QUORUM variable not set, launch with -e ZOOKEEPER_QUORUM=zookeeper:2181"
    exit 1
fi
if [[ -z "$AWS_ACCESS_KEY" || -z "$AWS_SECRET_KEY" || -z "$SECOR_S3_BUCKET"  ]]; then
	echo "Missing one or more S3 variables check AWS_ACCESS_KEY, AWS_SECRET_KEY, SECOR_S3_BUCKET"
    exit 1
fi

# validate s3 access
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY aws s3 ls s3://$SECOR_S3_BUCKET > /dev/null


COMMON_CONF=/opt/secor/secor.common.properties
PROD_CONF=/opt/secor/secor.prod.properties
# common conf
sed -i -e "s^aws.access.key=.*$^aws.access.key=${AWS_ACCESS_KEY}^" $COMMON_CONF
sed -i -e "s^aws.secret.key=.*$^aws.secret.key=${AWS_SECRET_KEY}^" $COMMON_CONF

sed -i -e "s/secor.compression.codec=.*$/secor.compression.codec=org.apache.hadoop.io.compress.SnappyCodec/" $COMMON_CONF
sed -i -e "s/secor.file.extension=.*$/secor.file.extension=.snappy/" $COMMON_CONF


# prod conf
sed -i -e "s/kafka.seed.broker.host=.*$/kafka.seed.broker.host=${KAFKA_SEED_BROKER_HOST}/" $PROD_CONF
sed -i -e "s/zookeeper.quorum=.*$/zookeeper.quorum=${ZOOKEEPER_QUORUM}/" $PROD_CONF
sed -i -e "s/secor.s3.bucket=.*$/secor.s3.bucket=${SECOR_S3_BUCKET}/" $PROD_CONF
sed -i -e "s/secor.max.file.size.bytes=.*$/secor.max.file.size.bytes=${SECOR_MAX_FILE_BYTES:-200000000}/" $PROD_CONF
sed -i -e "s/secor.max.file.age.seconds=.*$/secor.max.file.age.seconds=${SECOR_MAX_FILE_SECONDS:-3600}/" $PROD_CONF


KAFKA_TOPIC_FILTER=${SECOR_KAFKA_TOPIC_FILTER:-'.*'}
TIMESTAMP_NAME=${SECOR_TIMESTAMP_NAME:-timestamp}
TIMESTAMP_PATTERN=${SECOR_TIMESTAMP_PATTERN:-timestamp}
WRITER_FACTORY=${SECOR_WRITER_FACTORY:-com.pinterest.secor.io.impl.SequenceFileReaderWriterFactory}

# in COMMON_CONF
sed -i -e "s/secor.kafka.topic_filter=.*$/secor.kafka.topic_filter=${KAFKA_TOPIC_FILTER}/" $COMMON_CONF
sed -i -e "s/message.timestamp.name=.*$/message.timestamp.name=${TIMESTAMP_NAME}/" $COMMON_CONF
sed -i -e "s/message.timestamp.input.pattern=.*$/message.timestamp.input.pattern=${TIMESTAMP_PATTERN}/" $COMMON_CONF
sed -i -e "s/secor.file.reader.writer.factory=.*$/secor.file.reader.writer.factory=${WRITER_FACTORY}/" $COMMON_CONF

SECOR_GROUP=${SECOR_GROUP:-secor_backup}
SECOR_PARSER=${SECOR_MESSAGE_PARSER:-com.pinterest.secor.parser.OffsetMessageParser}

# target conf
cat <<EOF > /opt/secor/secor.prod.target.properties
# Generated by docker-entrypoint.sh

include=secor.prod.properties

# Name of the Kafka consumer group.
secor.kafka.group=$SECOR_GROUP

# Parser class that extracts partitions from consumed messages.
secor.message.parser.class=$SECOR_PARSER

# S3 path where sequence files are stored.
secor.s3.path=kafka/$SECOR_GROUP

# Local path where sequence files are stored before they are uploaded to s3.
secor.local.path=/tmp/$SECOR_GROUP

# Port of the Ostrich server.
ostrich.port=9999

EOF
cd /opt/secor
java -ea -Dsecor_group=$SECOR_GROUP -Dlog4j.configuration=file:./log4j.docker.properties -Dconfig=secor.prod.target.properties \
 -cp secor-0.6-SNAPSHOT.jar:lib/* com.pinterest.secor.main.ConsumerMain